
import React,{useEffect,useRef,useState}from"react";
import{socket}from"./socket";
import{extractYouTubeId,thumb}from"./youtube";
import type{RoomState,ChatMessage,Song}from"./types";
import{Music2,Sun,Moon,LogIn,Plus,Play,Pause,SkipForward,Volume2,VolumeX,Maximize2,MessageCircle,Users,Mic,MicOff,Headphones,Copy,Check,Crown,UserMinus,LogOut,Send,Smile,X,Radio,Wifi,Loader2}from"lucide-react";

declare global{interface Window{YT:any;onYouTubeIframeAPIReady?:()=>void}}

const fmt=(n:number)=>{const s=Math.max(0,Math.floor(n||0));return Math.floor(s/60)+":"+String(s%60).padStart(2,"0")};

function App(){
 const[view,setView]=useState<"home"|"room">(location.pathname.startsWith("/room/")?"room":"home");
 const[room,setRoom]=useState<RoomState|null>(null),[chat,setChat]=useState<ChatMessage[]>([]);
 const[name,setName]=useState(""),[roomName,setRoomName]=useState("Friday Night"),[password,setPassword]=useState("");
 const[joinCode,setJoinCode]=useState(location.pathname.startsWith("/room/")?location.pathname.split("/").pop()?.toUpperCase()||"":"");
 const[joinPass,setJoinPass]=useState(""),[error,setError]=useState(""),[theme,setTheme]=useState<"dark"|"light">("dark"),[online,setOnline]=useState(false);
 useEffect(()=>{document.documentElement.classList.toggle("light",theme==="light")},[theme]);
 useEffect(()=>{const c=()=>setOnline(true),d=()=>setOnline(false);socket.on("connect",c);socket.on("disconnect",d);return()=>{socket.off("connect",c);socket.off("disconnect",d)}},[]);
 useEffect(()=>{
  const rs=(s:RoomState)=>{setRoom(s);setView("room");if(location.pathname!=="/room/"+s.code)history.replaceState({}, "", "/room/"+s.code)};
  const cm=(m:ChatMessage)=>setChat(x=>[...x,m].slice(-200));
  const cr=(x:any)=>setChat(c=>c.map(m=>m.id===x.id?{...m,reactions:x.reactions}:m));
  const k=()=>{setRoom(null);setView("home");history.replaceState({},"","/");setError("You were removed from the room.")};
  socket.on("room:state",rs);socket.on("chat:message",cm);socket.on("chat:reaction",cr);socket.on("room:kicked",k);
  return()=>{socket.off("room:state",rs);socket.off("chat:message",cm);socket.off("chat:reaction",cr);socket.off("room:kicked",k)}
 },[]);
 const create=()=>{setError("");socket.connect();socket.emit("room:create",{name:roomName,userName:name,password:password||undefined},(r:any)=>r?.error?setError(r.error):(setRoom(r.state),setView("room"),history.replaceState({},"","/room/"+r.state.code)))};
 const join=()=>{setError("");socket.connect();socket.emit("room:join",{code:joinCode,userName:name,password:joinPass||undefined},(r:any)=>r?.error?setError(r.error):(setRoom(r.state),setChat(r.chat||[]),setView("room"),history.replaceState({},"","/room/"+r.state.code)))};
 if(view==="home"||!room)return <Home name={name} setName={setName} roomName={roomName} setRoomName={setRoomName} password={password} setPassword={setPassword} joinCode={joinCode} setJoinCode={setJoinCode} joinPass={joinPass} setJoinPass={setJoinPass} create={create} join={join} error={error} theme={theme} setTheme={setTheme} online={online}/>;
 return <Room room={room} chat={chat} theme={theme} setTheme={setTheme} onLeave={()=>{socket.disconnect();setRoom(null);setView("home");history.replaceState({},"","/")}}/>;
}

function Home(p:any){
 const[tab,setTab]=useState<"create"|"join">("create");
 return <div className="min-h-screen gradient-bg"><div className="noise"/>
 <header className="mx-auto flex max-w-6xl items-center justify-between px-5 py-6"><Logo/><div className="flex items-center gap-3"><span className="hidden text-xs text-white/40 sm:block">{p.online?"Connected":"Ready to connect"}</span><button onClick={()=>p.setTheme(p.theme==="dark"?"light":"dark")} className="glass rounded-full p-2">{p.theme==="dark"?<Sun size={17}/>:<Moon size={17}/>}</button></div></header>
 <main className="mx-auto grid max-w-6xl gap-10 px-5 pb-16 pt-10 lg:grid-cols-[1.1fr_.9fr] lg:items-center">
  <section><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-violet-400/20 bg-violet-400/10 px-3 py-1.5 text-xs font-semibold text-violet-200"><Radio size={13}/> Private real-time listening rooms</div><h1 className="text-5xl font-extrabold tracking-tight sm:text-7xl">Your music.<br/><span className="bg-gradient-to-r from-violet-300 via-fuchsia-300 to-cyan-300 bg-clip-text text-transparent">Your people.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-white/55 sm:text-lg">SyncBeat brings synchronized YouTube playback, queue, room chat and WebRTC voice into one private space.</p><div className="mt-8 flex flex-wrap gap-2 text-xs text-white/45"><span className="glass rounded-full px-3 py-2">Official YouTube embeds</span><span className="glass rounded-full px-3 py-2">WebRTC voice</span><span className="glass rounded-full px-3 py-2">No audio downloads</span></div></section>
  <section className="glass glow rounded-[28px] p-2"><div className="rounded-[22px] bg-black/20 p-6 sm:p-8"><div className="mb-6 flex rounded-xl bg-white/[.04] p-1"><button onClick={()=>setTab("create")} className={"flex-1 rounded-lg px-4 py-3 text-sm font-semibold "+(tab==="create"?"bg-white text-black":"text-white/50")}>Create room</button><button onClick={()=>setTab("join")} className={"flex-1 rounded-lg px-4 py-3 text-sm font-semibold "+(tab==="join"?"bg-white text-black":"text-white/50")}>Join room</button></div>
   {p.error&&<div className="mb-4 rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-200">{p.error}</div>}
   <Field label="Your name"><input value={p.name} onChange={e=>p.setName(e.target.value)} placeholder="e.g. Abhi" className="input"/></Field>
   {tab==="create"?<><Field label="Room name"><input value={p.roomName} onChange={e=>p.setRoomName(e.target.value)} className="input"/></Field><Field label="Password (optional)"><input type="password" value={p.password} onChange={e=>p.setPassword(e.target.value)} className="input"/></Field><button disabled={!p.name.trim()} onClick={p.create} className="action">Create private room <Plus size={16}/></button></>:<><Field label="Room code"><input value={p.joinCode} maxLength={6} onChange={e=>p.setJoinCode(e.target.value.toUpperCase())} placeholder="ABC123" className="input font-mono tracking-[.25em]"/></Field><Field label="Password (if required)"><input type="password" value={p.joinPass} onChange={e=>p.setJoinPass(e.target.value)} className="input"/></Field><button disabled={!p.name.trim()||p.joinCode.length!==6} onClick={p.join} className="action">Join room <LogIn size={16}/></button></>}
  </div></section>
 </main></div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="mb-4 block"><span className="mb-2 block text-xs font-semibold text-white/45">{label}</span>{children}</label>}
function Logo(){return <div className="flex items-center gap-2.5"><div className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-violet-400 to-cyan-300 text-black"><Music2 size={19}/></div><span className="text-lg font-extrabold">SyncBeat</span></div>}

function Room({room,chat,theme,setTheme,onLeave}:{room:RoomState;chat:ChatMessage[];theme:string;setTheme:any;onLeave:()=>void}){
 const[tab,setTab]=useState<"chat"|"people">("chat"),[add,setAdd]=useState(""),[notice,setNotice]=useState(""),[typing,setTyping]=useState(false),[low,setLow]=useState(false);
 const host=room.hostId===socket.id;
 const invite=location.href;
 const copy=async()=>{try{await navigator.clipboard.writeText(invite);setNotice("Invite link copied")}catch{setNotice(invite)}setTimeout(()=>setNotice(""),1800)};
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement)return;if(e.code==="Space"&&host){e.preventDefault();socket.emit("player:action",{type:room.isPlaying?"pause":"play"})}if(e.key.toLowerCase()==="c")document.getElementById("chat-input")?.focus()};window.addEventListener("keydown",fn);return()=>window.removeEventListener("keydown",fn)},[host,room.isPlaying]);
 const addSong=()=>{const id=extractYouTubeId(add);if(!id)return setNotice("Paste a valid YouTube URL or video ID");socket.emit("queue:add",{id,title:"YouTube video "+id,thumbnail:thumb(id),addedBy:"You"});setAdd("");setNotice("Added to queue");setTimeout(()=>setNotice(""),1200)};
 return <div className="min-h-screen gradient-bg"><div className="noise"/><header className="sticky top-0 z-20 border-b border-white/[.06] bg-[#07080c]/80 backdrop-blur-xl"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-4 py-3"><Logo/><div className="hidden items-center gap-2 rounded-full border border-white/10 bg-white/[.03] px-3 py-1.5 text-xs sm:flex"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400"/>{room.name}<span className="font-mono text-white/30">#{room.code}</span></div><div className="flex items-center gap-2"><button onClick={copy} className="hidden items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-xs sm:flex"><Copy size={14}/> Invite</button><button onClick={()=>setTheme(theme==="dark"?"light":"dark")} className="rounded-lg border border-white/10 p-2">{theme==="dark"?<Sun size={16}/>:<Moon size={16}/>}</button><button onClick={onLeave} className="rounded-lg border border-red-400/10 p-2 text-red-300"><LogOut size={16}/></button></div></div></header>
 <main className="mx-auto grid max-w-[1500px] gap-4 p-4 lg:grid-cols-[minmax(0,1fr)_380px]"><section><div className="mb-4 flex items-center justify-between gap-4"><div><div className="text-xs uppercase tracking-[.18em] text-violet-300/60">Listening together</div><h1 className="mt-1 text-2xl font-bold">{room.current?.title||"Nothing playing yet"}</h1></div><div className="flex items-center gap-2 text-xs text-white/35"><Wifi size={13}/> {room.participants.length} listening</div></div>
 <Player room={room} host={host} low={low}/>
 <div className="glass mt-4 rounded-2xl p-4"><div className="mb-3 flex items-center justify-between gap-3"><div><b className="text-sm">Queue</b><div className="text-xs text-white/30">{room.queue.length} {room.queue.length===1?"song":"songs"}</div></div><div className="flex gap-2"><input value={add} onChange={e=>setAdd(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addSong()} placeholder="Paste YouTube URL" className="w-44 rounded-lg border border-white/10 bg-white/[.04] px-3 py-2 text-xs"/><button onClick={addSong} className="rounded-lg bg-white px-3 text-black"><Plus size={15}/></button></div></div>{room.queue.length===0?<div className="rounded-xl border border-dashed border-white/10 py-8 text-center text-xs text-white/30">Queue is empty.</div>:room.queue.map((s,i)=><div key={s.id+i} draggable={host} className="mb-1 flex items-center gap-3 rounded-xl p-2 hover:bg-white/[.03]" onDragStart={e=>e.dataTransfer.setData("text/plain",String(i))} onDragOver={e=>e.preventDefault()} onDrop={e=>{const from=Number(e.dataTransfer.getData("text/plain"));if(Number.isInteger(from)&&from!==i)socket.emit("queue:reorder",from,i)}}><img src={s.thumbnail} className="h-10 w-16 rounded-md object-cover"/><div className="min-w-0 flex-1"><div className="truncate text-xs font-semibold">{s.title}</div><div className="text-[10px] text-white/30">Added by {s.addedBy}</div></div>{host&&<button onClick={()=>socket.emit("queue:remove",i)} className="rounded-lg p-2 text-red-300/60"><X size={14}/></button>}</div>)}</div>
 </section>
 <aside className="glass flex min-h-[640px] flex-col overflow-hidden rounded-2xl"><div className="flex border-b border-white/[.06]"><button onClick={()=>setTab("chat")} className={"flex-1 px-4 py-3 text-sm "+(tab==="chat"?"border-b-2 border-violet-400":"text-white/40")}><MessageCircle className="mr-2 inline" size={15}/>Chat</button><button onClick={()=>setTab("people")} className={"flex-1 px-4 py-3 text-sm "+(tab==="people"?"border-b-2 border-violet-400":"text-white/40")}><Users className="mr-2 inline" size={15}/>People</button></div>{tab==="chat"?<ChatBox chat={chat} typing={typing} setTyping={setTyping}/>:<People room={room} host={host}/>}<Voice low={low} setLow={setLow}/></aside></main>{notice&&<div className="fixed bottom-5 left-1/2 z-50 -translate-x-1/2 rounded-full border border-white/10 bg-[#151722] px-4 py-2 text-xs">{notice}</div>}</div>
}

function Player({room,host,low}:{room:RoomState;host:boolean;low:boolean}){
 const mount=useRef<HTMLDivElement>(null),yt=useRef<any>(null),[ready,setReady]=useState(false),[pos,setPos]=useState(room.position),[dur,setDur]=useState(0),[vol,setVol]=useState(70),[err,setErr]=useState("");
 const applying=useRef(false);
 useEffect(()=>{const init=()=>{if(!mount.current||!room.current)return;yt.current=new window.YT.Player(mount.current,{videoId:room.current.id,playerVars:{playsinline:1,controls:0,rel:0},events:{onReady:(e:any)=>{setReady(true);setDur(e.target.getDuration());e.target.setVolume(vol);e.target.seekTo(room.position,true);if(room.isPlaying)e.target.playVideo()},onStateChange:(e:any)=>{if(e.data===0&&host)socket.emit("player:action",{type:"ended"});if(e.data===-1)setErr("This video cannot be played in the YouTube embed. Choose another video.")}}})};if((window as any).YT?.Player)init();else window.onYouTubeIframeAPIReady=init;const t=setInterval(()=>{const p=yt.current;if(p?.getCurrentTime){const v=p.getCurrentTime();setPos(v);if(host&&p.getPlayerState?.()===1)socket.emit("player:action",{type:"seek",position:v})}},2000);return()=>{clearInterval(t);yt.current?.destroy?.();yt.current=null}},[room.current?.id]);
 useEffect(()=>{if(!ready||!yt.current)return;applying.current=true;const t=yt.current.getCurrentTime?.()||0;if(Math.abs(t-room.position)>1.2)yt.current.seekTo(room.position,true);if(room.isPlaying)yt.current.playVideo?.();else yt.current.pauseVideo?.();setTimeout(()=>applying.current=false,250)},[room.isPlaying,room.position,room.current?.id]);
 const action=(type:string)=>host&&socket.emit("player:action",{type});
 return <div className="glass overflow-hidden rounded-2xl"><div className="relative"><div ref={mount} className="yt-frame"/>{(!ready||err)&&<div className="absolute inset-0 grid place-items-center bg-[#090a0f]/80 p-6 text-center">{err?<div><div className="mx-auto mb-3 grid h-11 w-11 place-items-center rounded-full bg-red-400/10 text-red-300"><X/></div><p className="text-sm text-white/70">{err}</p><p className="mt-2 text-xs text-white/30">Embedding can be disabled by the video owner or limited by YouTube.</p></div>:<Loader2 className="animate-spin text-white/50"/>}</div>}</div><div className="p-4"><div className="flex items-center justify-between"><div className="text-xs text-white/35">{host?"Host controls playback":"Host controls playback"}{low&&" • low bandwidth"}</div><div className="flex gap-1"><button disabled={!host} onClick={()=>action(room.isPlaying?"pause":"play")} className="grid h-10 w-10 place-items-center rounded-full bg-white text-black disabled:opacity-30">{room.isPlaying?<Pause size={17}/>:<Play size={17} fill="currentColor"/>}</button><button disabled={!host||!room.queue.length} onClick={()=>room.queue[0]&&socket.emit("player:action",{type:"load",song:room.queue[0]})} className="rounded-lg p-2 disabled:opacity-30"><SkipForward size={18}/></button></div></div><input disabled={!host} type="range" min="0" max={dur||1} value={Math.min(pos,dur||1)} onChange={e=>{const v=Number(e.target.value);setPos(v);if(host){yt.current?.seekTo(v,true);socket.emit("player:action",{type:"seek",position:v})}}} className="range mt-3 w-full"/><div className="mt-1 flex justify-between text-[11px] text-white/30"><span>{fmt(pos)}</span><span>{fmt(dur)}</span></div><div className="mt-3 flex items-center gap-3"><button onClick={()=>{const v=vol?0:70;setVol(v);yt.current?.unMute?.();yt.current?.setVolume?.(v)}}>{vol?<Volume2 size={17}/>:<VolumeX size={17}/>}</button><input aria-label="volume" type="range" min="0" max="100" value={vol} onChange={e=>{const v=Number(e.target.value);setVol(v);yt.current?.unMute?.();yt.current?.setVolume?.(v)}} className="range w-24"/><button onClick={()=>yt.current?.getIframe?.()?.requestFullscreen?.()} className="ml-auto"><Maximize2 size={16}/></button></div></div></div>
}

function ChatBox({chat,typing,setTyping}:{chat:ChatMessage[];typing:boolean;setTyping:any}){
 const[text,setText]=useState(""),bottom=useRef<HTMLDivElement>(null);useEffect(()=>bottom.current?.scrollIntoView({behavior:"smooth"}),[chat]);
 const send=()=>{if(text.trim()){socket.emit("chat:send",text);setText("");socket.emit("chat:typing",false)}};
 return <><div className="scrollbar flex-1 overflow-y-auto p-4">{chat.map(m=><div key={m.id} className={"mb-3 "+(m.userId==="system"?"text-center":"")}><div className="flex items-baseline gap-2"><span className="text-xs font-semibold">{m.name}</span><span className="text-[9px] text-white/20">{m.userId!=="system"&&new Date(m.ts).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</span></div><div className="text-xs leading-5 text-white/65">{m.text}</div>{m.userId!=="system"&&<div className="mt-1 flex gap-1">{Object.entries(m.reactions).filter(([,v])=>v.length).map(([e,v])=><button key={e} onClick={()=>socket.emit("chat:react",{id:m.id,emoji:e})} className="rounded-full bg-white/[.05] px-2 py-0.5 text-[10px]">{e} {v.length}</button>)}<button onClick={()=>socket.emit("chat:react",{id:m.id,emoji:"❤️"})}>♡</button></div>}</div>)}<div ref={bottom}/>{typing&&<div className="text-[10px] text-white/25">Someone is typing…</div>}</div><div className="border-t border-white/[.06] p-3"><div className="flex gap-2"><button onClick={()=>setText((t:string)=>t+" 🙂")} className="rounded-lg p-2"><Smile size={16}/></button><input id="chat-input" value={text} onChange={e=>{setText(e.target.value);socket.emit("chat:typing",!!e.target.value);setTyping(!!e.target.value)}} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Message the room…" className="min-w-0 flex-1 rounded-lg border border-white/10 bg-white/[.04] px-3 py-2.5 text-xs"/><button onClick={send} className="rounded-lg bg-white p-2.5 text-black"><Send size={15}/></button></div></div></>
}

function People({room,host}:{room:RoomState;host:boolean}){return <div className="scrollbar flex-1 overflow-y-auto p-4">{room.participants.map(p=><div key={p.id} className="group flex items-center gap-3 rounded-xl p-2.5 hover:bg-white/[.03]"><div className="grid h-9 w-9 place-items-center rounded-full bg-white/5 text-xs font-bold">{p.name.slice(0,1).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">{p.name}{p.id===socket.id?" (you)":""}</p><div className="mt-1 flex items-center gap-2 text-[10px] text-white/30">{p.isHost&&<span className="inline-flex items-center gap-1 text-amber-300/70"><Crown size={10}/>Host</span>}{p.voiceJoined&&<Mic size={10}/>}</div></div>{host&&p.id!==socket.id&&<div className="flex gap-1 opacity-0 group-hover:opacity-100"><button onClick={()=>socket.emit("host:transfer",p.id)} className="rounded p-1.5"><Crown size={13}/></button><button onClick={()=>socket.emit("participant:kick",p.id)} className="rounded p-1.5 text-red-300"><UserMinus size={13}/></button></div>}</div>)}</div>}

function Voice({low,setLow}:{low:boolean;setLow:any}){
 const[joined,setJoined]=useState(false),[muted,setMuted]=useState(false),[deaf,setDeaf]=useState(false),[error,setError]=useState("");
 const local=useRef<MediaStream|null>(null),peers=useRef<Record<string,RTCPeerConnection>>({}),audios=useRef<Record<string,HTMLAudioElement>>({});
 const cfg=useRef<RTCConfiguration>({iceServers:[{urls:"stun:stun.l.google.com:19302"},{urls:"stun:stun1.l.google.com:19302"}]});
 useEffect(()=>{const base=import.meta.env.VITE_SERVER_URL||location.origin;fetch(base+"/config").then(r=>r.json()).then(x=>{if(x.stunUrls?.length)cfg.current={iceServers:x.stunUrls.map((u:string)=>({urls:u}))}}).catch(()=>{});
  const signal=async({peerId,data}:any)=>{if(!local.current)return;let pc=peers.current[peerId];if(!pc)pc=make(peerId);if(data?.type==="offer"){await pc.setRemoteDescription(data);const a=await pc.createAnswer();await pc.setLocalDescription(a);socket.emit("voice:signal",{peerId,data:pc.localDescription})}else if(data?.type==="answer")await pc.setRemoteDescription(data);else if(data?.candidate)await pc.addIceCandidate(data.candidate)};
  const joinedPeer=async({peerId}:any)=>{if(!local.current)return;const pc=make(peerId);const o=await pc.createOffer();await pc.setLocalDescription(o);socket.emit("voice:signal",{peerId,data:pc.localDescription})};
  const leftPeer=({peerId}:any)=>{peers.current[peerId]?.close();delete peers.current[peerId];audios.current[peerId]?.remove();delete audios.current[peerId]};
  socket.on("voice:signal",signal);socket.on("voice:peer-joined",joinedPeer);socket.on("voice:peer-left",leftPeer);
  function make(peerId:string){if(peers.current[peerId])return peers.current[peerId];const pc=new RTCPeerConnection(cfg.current);local.current?.getTracks().forEach(t=>pc.addTrack(t,local.current!));pc.onicecandidate=e=>e.candidate&&socket.emit("voice:signal",{peerId,data:{candidate:e.candidate}});pc.ontrack=e=>{let a=audios.current[peerId];if(!a){a=new Audio();a.autoplay=true;audios.current[peerId]=a}a.srcObject=e.streams[0];a.muted=deaf;a.volume=1};peers.current[peerId]=pc;return pc}
  return()=>{socket.off("voice:signal",signal);socket.off("voice:peer-joined",joinedPeer);socket.off("voice:peer-left",leftPeer);Object.values(peers.current).forEach(p=>p.close())}
 },[deaf]);
 const join=async()=>{setError("");try{local.current=await navigator.mediaDevices.getUserMedia({audio:true});socket.emit("voice:join");setJoined(true)}catch(e:any){setError(e?.name==="NotAllowedError"?"Microphone permission was denied.":"Could not access your microphone.")}};
 const leave=()=>{local.current?.getTracks().forEach(t=>t.stop());local.current=null;Object.values(peers.current).forEach(p=>p.close());peers.current={};socket.emit("voice:leave");setJoined(false)};
 const toggle=()=>{if(!local.current)return;const m=!muted;local.current.getAudioTracks().forEach(t=>t.enabled=!m);setMuted(m);socket.emit("voice:mute",m)};
 useEffect(()=>Object.values(audios.current).forEach(a=>a.muted=deaf),[deaf]);
 return <div className="border-t border-white/[.06] p-4"><div className="mb-3 flex items-center justify-between"><div><b className="text-xs">Voice room</b><div className="text-[10px] text-white/30">WebRTC peer audio</div></div>{joined&&<span className="text-[10px] text-emerald-300">Connected</span>}</div>{error&&<div className="mb-3 rounded-lg bg-red-400/10 p-2 text-[10px] text-red-200">{error}</div>}<div className="grid grid-cols-4 gap-2"><button onClick={joined?leave:join} className="col-span-2 rounded-lg bg-violet-500 px-2 py-2.5 text-xs font-semibold">{joined?<><LogOut className="mr-1 inline" size={14}/>Leave</>:<><Mic className="mr-1 inline" size={14}/>Join voice</>}</button><button disabled={!joined} onClick={toggle} className="rounded-lg border border-white/10 disabled:opacity-30">{muted?<MicOff className="mx-auto" size={15}/>:<Mic className="mx-auto" size={15}/>}</button><button disabled={!joined} onClick={()=>setDeaf((v:boolean)=>!v)} className={"rounded-lg border border-white/10 disabled:opacity-30 "+(deaf?"bg-red-400/10":"")}><Headphones className="mx-auto" size={15}/></button></div><label className="mt-3 flex items-center gap-2 text-[10px] text-white/30"><input type="checkbox" checked={low} onChange={e=>setLow(e.target.checked)}/>Low bandwidth mode</label><div className="mt-2 text-[10px] text-white/20">TURN is recommended for production voice.</div></div>
}
export default App;
